function data(){
var seznamVsehPostaj = [
{'ime': 'Antena Gorenjska', 'kodno': 'antena-gorenjska', 'stream': 'http://live1.radioantena.si/Antena-Gorenjska', 'slika': 'antena-gorenjska.png'},
{'ime': 'Antena Štajerska', 'kodno': 'antena-stajerska', 'stream': 'http://live1.radioantena.si/Antena-Stajerska', 'slika': 'antena-stajerska.png'},
{'ime': 'ARS', 'kodno': 'ars', 'stream': 'http://mp3.rtvslo.si/ars', 'slika': 'ars.png'},
{'ime': 'Center 80-a', 'kodno': 'center-80', 'stream': 'http://stream3.radiocenter.si:8064/;stream/1', 'slika': 'center-80.png'},
{'ime': 'Center Hit', 'kodno': 'center-hit', 'stream': 'http://stream3.radiocenter.si:9020/;stream/1', 'slika': 'center-hit.png'},
{'ime': 'Center Love', 'kodno': 'center-love', 'stream': 'http://stream3.radiocenter.si:8060/;stream/1', 'slika': 'center-love.png'},
{'ime': 'Center Mega Mix', 'kodno': 'center-mega-mix', 'stream': 'http://stream3.radiocenter.si:8066/;stream/1', 'slika': 'center-mega-mix.png'},
{'ime': 'Center Pop', 'kodno': 'center-pop', 'stream': 'http://stream3.radiocenter.si:8058/;stream/1', 'slika': 'center-pop.png'},
{'ime': 'Center Rock', 'kodno': 'center-rock', 'stream': 'http://stream3.radiocenter.si:8104/;stream/1', 'slika': 'center-rock.png'},
{'ime': 'Center YU', 'kodno': 'center-yu', 'stream': 'http://stream3.radiocenter.si:8100/;stream/1', 'slika': 'center-yu.png'},
{'ime': 'Koroški radio', 'kodno': 'koroski-radio', 'stream': 'http://shoutcast.netsi.net:8300/;stream.mp3', 'slika': 'koroski-radio.png'},
{'ime': 'Mister Deejay', 'kodno': 'mister-deejay', 'stream': 'http://stream.mister-deejay.com:9008/;', 'slika': 'mister-deejay.png'},
{'ime': 'Moj radio', 'kodno': 'moj-radio', 'stream': 'http://stream.strozak.org:8006', 'slika': 'moj-radio.png'},
{'ime': 'Murski val', 'kodno': 'murski-val', 'stream': 'http://89.142.197.238:8000/mv.mp3', 'slika': 'murski-val.png'},
{'ime': 'Primorski val', 'kodno': 'primorski-val', 'stream': 'http://212.44.99.35:8000/stream', 'slika': 'primorski-val.png'},
{'ime': 'Radio 1', 'kodno': 'radio-1', 'stream': 'http://live3.infonetmedia.si/Radio1', 'slika': 'radio-1.png'},
{'ime': 'Radio 24', 'kodno': 'radio-24', 'stream': 'http://onair.radio24.si:8000/live', 'slika': 'radio-24.png'},
{'ime': 'Radio 24 Narodnjak', 'kodno': 'radio-24-narodnjak', 'stream': 'http://onair.radio24.si:8000/narodnjak', 'slika': 'radio-24-narodnjak.png'},
{'ime': 'Radio 94', 'kodno': 'radio-94', 'stream': 'http://212.103.156.222:8000/lofi?type=.mp3/;stream/1', 'slika': 'radio-94.png'},
{'ime': 'Radio Aktual', 'kodno': 'radio-aktual', 'stream': 'http://195.95.158.131:9040/;stream.mp3', 'slika': 'radio-aktual.png'},
{'ime': 'Radio Aktual Dalmacija', 'kodno': 'radio-aktual-dalmacija', 'stream': 'http://195.95.158.131:9075/;stream.mp3', 'slika': 'radio-aktual-dalmacija.png'},
{'ime': 'Radio Aktual Latino', 'kodno': 'radio-aktual-latino', 'stream': 'http://195.95.158.131:9045/;stream.mp3', 'slika': 'radio-aktual-latino.png'},
{'ime': 'Radio Antena', 'kodno': 'radio-antena', 'stream': 'http://live1.radioantena.si/Anten', 'slika': 'radio-antena.png'},
{'ime': 'Radio Capodistria', 'kodno': 'radio-capodistria', 'stream': 'http://mp3.rtvslo.si/capo', 'slika': 'radio-capodistria.png'},
{'ime': 'Radio Capris', 'kodno': 'radio-capris', 'stream': 'http://stream02.exit.si:8000/live', 'slika': 'radio-capris.png'},
{'ime': 'Radio Capris 90\'s', 'kodno': 'radio-capris-90', 'stream': 'http://stream02.exit.si:8000/90', 'slika': 'radio-capris-90.png'},
{'ime': 'Radio Capris Capital', 'kodno': 'radio-capris-capital', 'stream': 'http://stream02.exit.si:8000/ITA', 'slika': 'radio-capris-capital.png'},
{'ime': 'Radio Capris Dalmacija', 'kodno': 'radio-capris-dalmacija', 'stream': 'http://stream02.exit.si:8000/DALMACIJA', 'slika': 'radio-capris-dalmacija.png'},
{'ime': 'Radio Capris Ex-Yu', 'kodno': 'radio-capris-ex-yu', 'stream': 'http://stream02.exit.si:8000/EXYU', 'slika': 'radio-capris-ex-yu.png'},
{'ime': 'Radio Capris Hits', 'kodno': 'radio-capris-hits', 'stream': 'http://stream02.exit.si:8000/HITS', 'slika': 'radio-capris-hits.png'},
{'ime': 'Radio Capris Klasik', 'kodno': 'radio-capris-klasik', 'stream': 'http://stream02.exit.si:8000/KLASIK', 'slika': 'radio-capris-klasik.png'},
{'ime': 'Radio Capris Rock', 'kodno': 'radio-capris-rock', 'stream': 'http://stream02.exit.si:8000/ROCK', 'slika': 'radio-capris-rock.png'},
{'ime': 'Radio Capris SLO', 'kodno': 'radio-capris-slo', 'stream': 'http://stream02.exit.si:8000/SLO', 'slika': 'radio-capris-slo.png'},
{'ime': 'Radio Celje', 'kodno': 'radio-celje', 'stream': 'http://89.142.196.111:9030/;stream.mp3', 'slika': 'radio-celje.png'},
{'ime': 'Radio Center', 'kodno': 'radio-center', 'stream': 'http://stream2.radiocenter.si:8000/;stream/1', 'slika': 'radio-center.png'},
{'ime': 'Radio City', 'kodno': 'radio-city', 'stream': 'http://82.149.22.34:8000/CityMp364mono.mp3', 'slika': 'radio-city.png'},
{'ime': 'Radio Dur', 'kodno': 'radio-dur', 'stream': 'http://ph.dur.si/dur?type=.mp3/;stream.mp3', 'slika': 'radio-dur.png'},
{'ime': 'Radio Ekspres', 'kodno': 'radio-ekspres', 'stream': 'http://93.103.13.156:8000/;stream/1', 'slika': 'radio-ekspres.png'},
{'ime': 'Radio Europa 05', 'kodno': 'radio-europa-05', 'stream': 'http://78.129.224.17:6652/;stream.mp3', 'slika': 'radio-europa-05.png'},
{'ime': 'Radio Gorenc', 'kodno': 'radio-gorenc', 'stream': 'http://www.radiogorenc.si:8000/radiogorenc.mp3?type=.mp3/;stream.mp3', 'slika': 'radio-gorenc.png'},
{'ime': 'Radio Hit', 'kodno': 'radio-hit', 'stream': 'http://stream02.exit.si:8000/radiohit', 'slika': 'radio-hit.png'},
{'ime': 'Radio Koper', 'kodno': 'radio-koper', 'stream': 'http://mp3.rtvslo.si/rakp', 'slika': 'radio-koper.png'},
{'ime': 'Radio Krka', 'kodno': 'radio-krka', 'stream': 'http://93.103.12.127:8000/;stream/1', 'slika': 'radio-krka.png'},
{'ime': 'Radio Kum', 'kodno': 'radio-kum', 'stream': 'http://195.95.158.131:7010/;stream.mp3', 'slika': 'radio-kum.png'},
{'ime': 'Radio Laser', 'kodno': 'radio-laser', 'stream': 'http://shoutcast.netsi.net:8100/;', 'slika': 'radio-laser.png'},
{'ime': 'Radio Maribor', 'kodno': 'radio-maribor', 'stream': 'http://mp3.rtvslo.si/rmb', 'slika': 'radio-maribor.png'},
{'ime': 'Radio Marš', 'kodno': 'radio-mars', 'stream': 'http://frekvenca.eu:8000/radiomars.mp3', 'slika': 'radio-mars.png'},
{'ime': 'Radio Maxi', 'kodno': 'radio-maxi', 'stream': 'http://46.150.34.194:8010/;stream.mp3', 'slika': 'radio-maxi.png'},
{'ime': 'Radio MMR', 'kodno': 'radio-mmr', 'stream': 'http://mp3.rtvslo.si/mmr', 'slika': 'radio-mmr.png'},
{'ime': 'Radio NET FM', 'kodno': 'radio-net-fm', 'stream': 'http://spletniradio.si-shell.net:8010/;', 'slika': 'radio-net-fm.png'},
{'ime': 'Radio Ognjišče', 'kodno': 'radio-ognjišče', 'stream': 'http://real.ognjisce.si:8000/ognjisce.mp3?type=.mp3/;stream/1', 'slika': 'radio-ognjisce.png'},
{'ime': 'Radio Potepuh', 'kodno': 'radio-potepuh', 'stream': 'http://193.105.67.24:8094', 'slika': 'radio-potepuh.png'},
{'ime': 'Radio Prlek', 'kodno': 'radio-prlek', 'stream': 'http://89.212.242.158:8000/;stream.mp3', 'slika': 'radio-prlek.png'},
{'ime': 'Radio Prvi', 'kodno': 'radio-prvi', 'stream': 'http://mp3.rtvslo.si/ra1', 'slika': 'radio-prvi.png'},
{'ime': 'Radio Ptuj', 'kodno': 'radio-ptuj', 'stream': 'http://stream.radio-ptuj.si:8000/;stream.mp3', 'slika': 'radio-ptuj.png'},
{'ime': 'Radio Rakitna', 'kodno': 'radio-rakitna', 'stream': 'http://ph.dur.si/dursi', 'slika': 'radio-rakitna.png'},
{'ime': 'Radio Robin', 'kodno': 'radio-robin', 'stream': 'http://live3.infonetmedia.si/Robin?type=.mp3/;stream/1', 'slika': 'radio-robin.png'},
{'ime': 'Radio Rogla', 'kodno': 'radio-rogla', 'stream': 'http://193.105.67.24:8010', 'slika': 'radio-rogla.png'},
{'ime': 'Radio Rogla - Dalmacija', 'kodno': 'radio-rogla-dalmacija', 'stream': 'http://193.105.67.24:8012', 'slika': 'radio-rogla-dalmacija.png'},
{'ime': 'Radio Rogla - Najlepše ljubezenske', 'kodno': 'radio-rogla-najlepse-ljubezenske', 'stream': 'http://193.105.67.24:8018', 'slika': 'radio-rogla-najlepse-ljubezenske.png'},
{'ime': 'Radio Rogla - po domače', 'kodno': 'radio-rogla-po-domace', 'stream': 'http://193.105.67.24:8016', 'slika': 'radio-rogla-po-domace.png'},
{'ime': 'Radio Rogla - Rock', 'kodno': 'radio-rogla-rock', 'stream': 'http://193.105.67.24:8014', 'slika': 'radio-rogla-rock.png'},
{'ime': 'Radio S', 'kodno': 'radio-s', 'stream': 'http://live4.infonetmedia.si/radios', 'slika': 'radio-s.png'},
{'ime': 'Radio Salomon', 'kodno': 'radio-salomon', 'stream': 'http://195.95.158.131:8050/;stream.mp3', 'slika': 'radio-salomon.png'},
{'ime': 'Radio Salomon Dance Now', 'kodno': 'radio-salomon-dance-now', 'stream': 'http://195.95.158.129:7065/;', 'slika': 'radio-salomon-dance-now.png'},
{'ime': 'Radio Si', 'kodno': 'radio-si', 'stream': 'http://mp3.rtvslo.si/rsi', 'slika': 'radio-si.png'},
{'ime': 'Radio Slovenske Gorice', 'kodno': 'radio-slovenske-gorice', 'stream': 'http://91.185.194.102:8014/;stream.mp3', 'slika': 'radio-slovenske-gorice.png'},
{'ime': 'Radio Sora', 'kodno': 'radio-sora', 'stream': 'http://radio-sora.si:8000/radio-sora.mp3', 'slika': 'radio-sora.png'},
{'ime': 'Radio Sraka', 'kodno': 'radio-sraka', 'stream': 'http://193.105.67.24:8006', 'slika': 'radio-sraka.png'},
{'ime': 'Radio Študent', 'kodno': 'radio-student', 'stream': 'http://kruljo.radiostudent.si:8000/midq', 'slika': 'radio-student.png'},
{'ime': 'Radio Terminal', 'kodno': 'radio-terminal', 'stream': 'http://live.radioterminal.si/live', 'slika': 'radio-terminal.png'},
{'ime': 'Radio Tomi', 'kodno': 'radio-tomi', 'stream': 'http://93.103.130.12:8080/tomi.mp3', 'slika': 'radio-tomi.png'},
{'ime': 'Radio Top', 'kodno': 'radio-top', 'stream': 'http://193.105.67.24:8024', 'slika': 'radio-top.png'},
{'ime': 'Radio Triglav', 'kodno': 'radio-triglav', 'stream': 'http://www.radiotriglav.si:8000/;stream.mp3', 'slika': 'radio-triglav.png'},
{'ime': 'Radio Velenje', 'kodno': 'radio-velenje', 'stream': 'http://212.18.39.42:8000/;stream.mp3', 'slika': 'radio-velenje.png'},
{'ime': 'Radio Veseljak', 'kodno': 'radio-veseljak', 'stream': 'http://195.95.158.131:9060/;stream/1', 'slika': 'radio-veseljak.png'},
{'ime': 'Rock radio', 'kodno': 'rock-radio', 'stream': 'http://stream.rockradio.si:9034/;stream/1', 'slika': 'rock-radio.svg'},
{'ime': 'Šport 202', 'kodno': 'sport-202', 'stream': 'http://mp3.rtvslo.si/sportval202', 'slika': 'sport-202.png'},
{'ime': 'Štajerski val', 'kodno': 'stajerski-vrt', 'stream': 'http://stream.stajerskival.si:8004/;mp3', 'slika': 'stajerski-val.png'},
{'ime': 'Val 202', 'kodno': 'val-202', 'stream': 'http://mp3.rtvslo.si/val202', 'slika': 'val-202.svg'},
{'ime': 'Veseljakova pumpa', 'kodno': 'veseljakova-pumpa', 'stream': 'http://195.95.158.129:7070/;stream/1', 'slika': 'veseljakova-pumpa.png'},
{'ime': 'Zeleni Val', 'kodno': 'zeleni-val', 'stream': 'http://stream77.pfe.technology:8000/zelenival.mp3', 'slika': 'zeleni-val.png'}
];
return seznamVsehPostaj;
}